apiVersion: apps/v1
kind: Deployment
metadata:
  name: fm-app
  namespace: prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fm-app
    spec:
      containers:
        - name: fm-app
          image: "205930631794.dkr.ecr.us-east-1.amazonaws.com/fm_app:9.78"
        - name: fm-app-celery
          image: "205930631794.dkr.ecr.us-east-1.amazonaws.com/fm_app:9.78"
